
[package]
name = "smile-wasm"
version = "0.1.0"
authors = [ "harapan <harapanpardamean@gmail.com>" ]
edition = "2018"

[lib]
crate-type = [ "cdylib" ]

[build-dependencies]
wasm-bindgen-test = "0.2"

[dependencies]
wasm-bindgen = "0.2.50"
